name: Update Live Demo

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-demo]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /srv/masscodeweb
            docker compose pull
            docker compose up -d --force-recreate